FROM golang:1.17.5-alpine3.15

WORKDIR /cloud-native

RUN apk update && apk add --no-cache gcc musl-dev git bash

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -ldflags '-w -s' -a -o ./bin/app ./cmd/app \
    && go build -ldflags '-w -s' -a -o ./bin/migrate ./cmd/migrate

EXPOSE 8080

CMD ["/cloud-native/bin/app"]
