# Build stage
FROM golang:1.17.5-alpine3.15 as build-stage
WORKDIR /cloud-native

RUN apk update && apk add --no-cache gcc musl-dev git
COPY . .
RUN go build -ldflags '-w -s' -a -o ./bin/app ./cmd/app

# Deploy stage
FROM alpine:3.15
RUN apk update && apk add --no-cache bash

COPY --from=build-stage /cloud-native/bin/app /cloud-native/

EXPOSE 8080
CMD ["/cloud-native/app"]
